version: 0.0
os: linux
files:
  - source: build
    destination: /opt/voyager/app
hooks:
  BeforeInstall:
    - location: scripts/before_install
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/validate_service
      timeout: 300
      runas: root